<p>Simple:</p>

<pre><code>#include &lt;stdexcept&gt;

int compare( int a, int b ) {
    if ( a &lt; 0 || b &lt; 0 ) {
        throw std::invalid_argument( "received negative value" );
    }
}
</code></pre>

<p>The Standard Library comes with a nice collection of <a href="http://stdcxx.apache.org/doc/stdlibref/2-3.html">built-in exception objects</a> you can throw.  Keep in mind that you should always throw by value and catch by reference:</p>

<pre><code>try {
    compare( -1, 3 );
}
catch( const std::invalid_argument&amp; e ) {
    // do stuff with exception... 
}
</code></pre>

<p>You can have multiple catch() statements after each try, so you can handle different exception types separately if you want.  </p>

<p>You can also re-throw exceptions:</p>

<pre><code>catch( const std::invalid_argument&amp; e ) {
    // do something

    // let someone higher up the call stack handle it if they want
    throw e;
}
</code></pre>

<p>And to catch exceptions regardless of type:</p>

<pre><code>catch( ... ) { };
</code></pre>
