<p>You can capture the exception object and examine it.</p>

<pre><code>try:
    res = f(arg1)
except TypeError as e:
    if "f() missing 1 required positional argument" in e.args[0]: 
        res = f(arg1, arg2)
    else:
        raise
</code></pre>

<p>Frankly, though, not going the extra length to classify the exception should work fine as you should be getting both the original traceback and the secondary traceback if the error originated inside f() -- debugging should not be a problem.</p>

<p>Also, if you have control over f() you can make second argument optional and not have to second-guess it:</p>

<pre><code>def f(a, b=None):
    pass
</code></pre>

<p>Now you can call it either way.</p>

<p>How about this:</p>

<pre><code>import inspect

if len(inspect.getargspec(f).args) == 1:
    res = f(arg1)
else:
    res = f(arg1, arg2)
</code></pre>
