<p>This happens because the object is new, and is not saved yet. There for it has not got a primary-key. If you save a object that has been saved before, this error should not happen.</p>

<p>Why don't you use post_save. In post_save the object has been saved, and therefore has a primary key. If you have to use pre_save you can check if instance.id exist. If it don't exist, you can't have any tags (since a object has to have a primary id for ManyToMany-fields to work (hence the exception))</p>

<p>To test for a primary-key, you can do something like this:</p>

<pre><code>@receiver(pre_save, sender=Book)
def pre_save_tags(sender, instance, **kwargs):
    # tags is a many-to-many relation
    if instance.id:
        print instance.tags
</code></pre>
