<p>You should throw another error in the catch block. Or not catch the initial error at all.</p>

<p>Currently, the following happens:</p>

<pre><code>&lt;error condition me&gt;
throw "error"
catch error and  Show alert
</code></pre>

<p>To "halt" the execution, you have to add <code>throw e</code> after the alert (in the <code>catch</code> block):</p>

<pre><code>catch(e) {
    alert('error occurred');
    throw e;
}
</code></pre>

<p>If your function is called from within another try-catch block, you also have to apply a similar mechanism to that block.</p>
