<p>The answer will probably not be relevant to many people, but as Anton pointed out, that it is an issue to do with the promise loading asynchronously.</p>

<p>I had an event that was calling the same promise at the same time. As soon as I remove the trigger to that event, I don't get any errors. </p>
